
title: "DeepRob: Deep Learning for Robot Perception"
tagline: Deep Learning for Robot Perception
description: This course covers the necessary background of neural-network-based deep learning for robot perception – building on advancements in computer vision that enable robots to physically manipulate objects
author: Anthony Opipari
baseurl: '/w25' # the subpath of your site, e.g. /blog
url: 'https://deeprob.org' # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/logos/favicons/UMich_favicon_light.png"
destination: _site/w25/

ga_tracking: G-FX9SVF3WSQ
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.7.0
color_scheme: mich
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links_new_tab: true
aux_links:
  Forum:
    - https://piazza.com/class/m4pgejar4ua2qf
  OH Queue:
    - https://oh.eecs.umich.edu/course_queues/884
  Autograder:
    - https://autograder.io/web/course/299
  Google Drive:
    - https://drive.google.com/drive/folders/1vOz1SA_fb1ebIe0JIaFMHA3AdwKkh7sG?usp=drive_link
  '<img src="/w25/assets/logos/UMRobotics.png" alt="Link to Michigan Robotics website" class="nav-img">':
    - 'https://robotics.umich.edu/'
  

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:

# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

callouts:
  highlight:
    color: yellow
  note:
    title: Note
    color: purple

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - .github/
  - .git/
  - assets/slides/
