name: Build & Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build main
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      # - name: Checkout W23
      #   uses: actions/checkout@v4
      #   with:
      #     ref: w23
      #     path: repo_w23
      #     fetch-depth: 1

      # - name: Build W23 with Jekyll
      #   run: |
      #     bundle exec jekyll build \
      #       --source "${{ github.workspace }}/repo_w23" \
      #       --destination "${{ github.workspace }}/_site/w23" \
      #       --config "${{ github.workspace }}/repo_w23/_config.yml"
      #   env:
      #     JEKYLL_ENV: production
      #     BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile

      # - name: Checkout W24
      #   uses: actions/checkout@v4
      #   with:
      #     ref: w24
      #     path: repo_w24
      #     fetch-depth: 1

      # - name: Build W24 with Jekyll
      #   run: |
      #     bundle exec jekyll build \
      #       --source "${{ github.workspace }}/repo_w24" \
      #       --destination "${{ github.workspace }}/_site/w24" \
      #       --config "${{ github.workspace }}/repo_w24/_config.yml"
      #   env:
      #     JEKYLL_ENV: production
      #     BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile

      - name: Checkout W25
        uses: actions/checkout@v4
        with:
          ref: w25
          path: repo_w25
          fetch-depth: 1

      - name: Build W25 with Jekyll
        run: |
          bundle exec jekyll build \
            --source "${{ github.workspace }}/repo_w25" \
            --destination "${{ github.workspace }}/_site/w25" \
            --config "${{ github.workspace }}/repo_w25/_config.yml"
        env:
          JEKYLL_ENV: production
          BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile

      - name: Checkout W26
        uses: actions/checkout@v4
        with:
          ref: w26
          path: repo_w26
          fetch-depth: 1

      - name: Build W26 with Jekyll
        run: |
          bundle exec jekyll build \
            --source "${{ github.workspace }}/repo_w26" \
            --destination "${{ github.workspace }}/_site/w26" \
            --config "${{ github.workspace }}/repo_w26/_config.yml"
        env:
          JEKYLL_ENV: production
          BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile

      - name: Show output sizes
        run: |
          echo "_site breakdown:"
          du -h -d 3 _site | sort -hr | head -n 80

      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
